Repository prgrms-be-devcourse/NBB1_1_3_Team09, pull requests merged in 2024-11, with the labels that each got.

#19 Feature/#17 여행비 항목별로 미리 설정할 수 있는 기능 추가
  src/main/kotlin/com/grepp/nbe1_3_team9/common/exception/exceptions/FinancialPlanException.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/AccountBookController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/ExchangeRateController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/FinancialPlanController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/accountBook/AccountBookAllResp.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/accountBook/AccountBookOneResp.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/accountBook/AccountBookReq.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/accountBook/ReceiptDTO.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/accountBook/UpdateAccountBookReq.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/exchangeRate/ExchangeRateReqDTO.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/exchangeRate/ExchangeRateResDTO.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/financialPlan/AddFinancialPlanReq.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/financialPlan/DeleteFinancialPlanReq.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/dto/financialPlan/FinancialPlanDTO.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/finance/ExchangeRate.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/finance/Expense.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/finance/FinancialPlan.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/group/Group.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/finance/AccountBookRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/finance/ExchangeRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/finance/FinancialPlanRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/finance/AccountBookService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/finance/ExchangeRateService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/finance/FinancialPlanService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/finance/OCRService.kt
Labels: ✨ Feature

#25 Group 양방향 관계 개선
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/group/Group.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/group/membership/GroupMembershipRepositoryCustom.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/group/membership/GroupMembershipRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/group/GroupService.kt
Labels: 🔨 Refactor

#23 Feat: redis 비관적 락(수정,삭제를 위한 일정 조회시 lock걸기) 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/redis/RedisConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/common/exception/ExceptionMessage.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/event/EventLocationController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/event/dto/UnlockLocationRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/event/EventLocationService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/location/LocationApiService.kt
Labels: ✨ Feature

#30 Feature/#8 OAuth2 서비스 구조 최적화
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/config/SecurityConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/jwt/JwtFilter.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/jwt/JwtUtil.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/service/oauth2/KakaoApiService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/service/oauth2/KakaoUserInfo.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/service/oauth2/OAuth2ApiService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/service/oauth2/OAuth2UserInfo.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/service/oauth2/handler/OAuth2LoginFailureHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/service/oauth2/handler/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/common/config/CacheConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/user/UserController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/user/UserRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/user/UserService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/controller/NotificationController.kt
Labels: 🔨 Refactor, ✨ Feature

#27 feature/#26
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/controller/dto/NotificationDto.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/controller/dto/NotificationResp.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/entity/Notification.kt
Labels: 🔨 Refactor

#32 Feature/#31 날씨 서비스 kotlin migration 및 기타 기능 수정
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/config/SecurityConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/admin/redis/RedisConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/common/config/CacheConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/weather/WeatherController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/weather/dto/GeocodeRes.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/user/UserRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/weather/WeatherService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/controller/dto/NotificationResp.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/entity/Notification.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/repository/NotificationRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/notification/service/NotificationService.kt
Labels: 🔨 Refactor, ✨ Feature

#34 Fix: 챗봇 오류 수정
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/chatBot/ChatBotController.kt
Labels: 🐞 BugFix

#36 Feature/#35 가계부 group대신 event로 연결 변경
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/AccountBookController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/finance/FinancialPlanController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/finance/Expense.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/entity/finance/FinancialPlan.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/event/eventrepo/EventRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/finance/AccountBookRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/finance/FinancialPlanRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/finance/AccountBookService.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/finance/FinancialPlanService.kt
Labels: 🔨 Refactor

#37 Feature/#10 CI/CD 기본 설정 완료
  Dockerfile
  build.gradle.kts
  docker/app/docker-compose.yml
  docker/app/my.cnf
  docker/monitoring/docker-compose.yml
  docker/monitoring/prometheus.yml
  src/main/kotlin/com/grepp/nbe1_3_team9/controller/user/UserController.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/group/membership/GroupMembershipRepositoryCustom.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/repository/group/membership/GroupMembershipRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team9/domain/service/user/UserService.kt
Labels: 🌏 Deploy, ✨ Feature

#39 Fix: application.yaml 파일 외부에서 마운트하도록 설정
  Dockerfile
Labels: 🌏 Deploy
